### ISSUE TITLE
Admin login doesn't seem to be working

### ISSUE THREAD

**Issue by wley3337** [VilllageBookBuilders/backend-vbb-portal#49]
Trying to log in with the super user name and password, you get a `FieldError`

 ![Screen Shot 2021-04-08 at 9.15.36 PM.png](https://images.zenhubusercontent.com/6002e09bfa03b229d84ca4dd/14a48b5f-49bc-4982-918b-97852a3992b6)

**Comment by vigneshhari** [comment]
Issue is now resolved, I will create accounts with each user type and share via slack.
